version: '2' 

services:
    postgres:
        image: debezium/postgres:12 
        hostname: postgres 
        container_name: postgres 
        ports:
            - "5437:5432"
        environment:
            POSTGRES_USER: postgres-user 
            POSTGRES_PASSWORD: postgres-pw
            POSTGRES_DB: customers 
        volumes:
            - "./postgres/custom-config.conf:/etc/postgresql/postgres.conf"
        #command: postgres -c config_file=/etc/postgresql/postgresql.conf 