version: '2' 

services:
    elastic:
        image: elasticsearch:7.6.2 
        hostname: elastic 
        ports:
            - "9200:9200" 
            - "9300:9300" 
        environment:
            discovery.type: single-node 