version: '3'
services:
  kafka:
    image: confluentinc/cp-kafka:5.3.0-1 
    container_name: kafka 
    restart: unless-stopped 
    network_mode: host 

    volumes:
      - /var/lib/kafka/data:/var/lib/kafka/data 
      - /var/log/kafka:/var/log/kafka 
    environment:
      KAFKA_HEAP_OPTS: '-Xms4g -Xmx4g' 
      KAFKA_JMX_OPTS: '-Djava.rmi.server.hostname=192.2.0.21 -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=10030 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false'
      KAFKA_BROKER_ID: 0 
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092 
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.2.0.21:9092 
      KAFKA_ZOOKEEPER_CONNECT: 192.2.0.11:2181;192.2.0.12:2181;192.2.0.13:2181
      KAFKA_LOG_RETENTION_HOURS: 768 
      #KAFKA_LOG_RETENTION_BYTES: 1073741824 
      #KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000 
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true' 
      KAFKA_NUM_PARTITIONS: 6 
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2 



    